### ISSUE TITLE
Integration error with todo

### ISSUE THREAD

**Issue by ienjoybeer** [kevdliu/hacs-anylist#4]
I'm unable to see any entities or lists from this integration. I successfully installed the AddOn and I believe have it configured correctly. This is what I see in the debug log:

2023-12-02 17:56:31.828 INFO (MainThread) [homeassistant.setup] Setting up anylist
2023-12-02 17:56:31.828 INFO (MainThread) [homeassistant.setup] Setup of domain anylist took 0.0 seconds
2023-12-02 17:56:37.792 INFO (MainThread) [homeassistant.components.todo] Setting up todo.anylist
2023-12-02 17:56:38.328 ERROR (MainThread) [homeassistant.components.todo] Error while setting up anylist platform for todo
  File "/config/custom_components/anylist/todo.py", line 13, in async_setup_entry
  File "/config/custom_components/anylist/__init__.py", line 206, in get_lists

**Comment by kevdliu** [comment]
Hi @ienjoybeer, are there any more lines below the logs you posted that specifies the exception or error?

**Comment by ienjoybeer** [comment]
2023-12-02 17:56:38.328 ERROR (MainThread) [homeassistant.components.todo] Error while setting up anylist platform for todo
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/anylist/todo.py", line 13, in async_setup_entry
    code, lists = await hass.data[DOMAIN].get_lists()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/anylist/__init__.py", line 206, in get_lists
    async with session.get(self.get_server_url("lists")) as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 984, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.xxx.xxx:8080 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)]

**Comment by kevdliu** [comment]
Interesting that it's complaining about SSL version mismatch. Did you specify http:// when configuring the server URL? Do you have the server behind a reverse proxy?

**Comment by ienjoybeer** [comment]
I tried both http and https actually. No reverse proxy.

**Comment by kevdliu** [comment]
Can you try going to `http://<server ip>:<server port>/lists` in your web browser? Server port is the port you set in the addon's config, default being 8080

**Comment by ienjoybeer** [comment]
I should have thought of that. Going to that page, it returns this:

Cannot GET /

**Comment by ienjoybeer** [comment]
<img width="1069" alt="image" src="https://github.com/kevdliu/hacs-anylist/assets/130024895/61ecc1d7-95a1-4223-85f0-69c3fef03aac">

**Comment by kevdliu** [comment]
Did you include the trailing "/lists" in the URL?
